name: nalysys-terraform-cd-dev

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".gitignore"
      - "**.md"
      - "docs/**"

env:
  TF_VERSION: 1.3.8
  TFNOTIFY_VERSION: v1.5.1

jobs:
  terraform_apply_dev:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: authenticate to gcp
        uses: google-github-actions/auth@v0
        with:
          service_account: ${{ secrets.DEV_GCP_SVC_ACCOUNT }}
          workload_identity_provider: ${{ secrets.DEV_GCP_OIDC_PROVIDER }}

      - name: set up terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: terraform apply
        run: |
          bash ./bin/apply.sh dev nalysys-infra
