name: nalysys-terraform-ci-manual

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: env value
        required: true
        options:
          - "dev"

env:
  TF_VERSION: 1.3.8
  TFCMT_VERSION: v3.4.0

jobs:
  terraform_plan_dev:
    if: github.event.inputs.env == 'dev'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: authenticate to gcp
        uses: google-github-actions/auth@v0
        with:
          service_account: ${{ secrets.DEV_GCP_SVC_ACCOUNT }}
          workload_identity_provider: ${{ secrets.DEV_GCP_OIDC_PROVIDER }}

      - name: set up tfcmt
        run: sudo bash ./bin/tfcmt.sh ${{ env.TFCMT_VERSION }}

      - name: set up terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: terraform plan
        run: |
          tfcmt \
          --config ./.tfcmt/github.yml \
          --var target:NalysysDev plan -- bash ./bin/plan.sh dev nalysys-infra
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          PR_NUMBER: ${{ github.event.number }}
